Related match
skohub-io/skohub-vocabs pull request #117
Opened 2020-12-21 14:41 UTC by sroertgen

Based on #106 I also added `skos:relatedMatch`.

I'm not that experienced with GraphQL, so I hope adding that type in `src/types.js` was the correct way of doing things.

This will close #116.

2020-12-22 15:37 UTC, literarymachine reviewed
Looks good to me, I would suggest we also add the other SKOS mapping relations mentioned in https://github.com/skohub-io/skohub-vocabs/issues/109.

2021-01-04 08:33 UTC, acka47 requested changes
What @literarymachine said: We should also add the other mapping relations in this PR.

2021-01-05 13:03 UTC, acka47 approved these changes

2021-01-06 20:23 UTC, literarymachine approved these changes

2021-01-06 20:28 UTC, literarymachine requested changes
The mapping relations still have to be added to the HTML templates.

2021-01-06 20:28 UTC, literarymachine commented on src/components/Concept.js
> +    {concept.related
Array length needs to be checked here in order to fix what @acka47 describes in https://github.com/skohub-io/skohub-vocabs/issues/105#issuecomment-753824382

2021-01-06 20:33 UTC, sroertgen commented on src/components/Concept.js
> +    {concept.related
ok, will do that. Was not sure, if this was wanted (https://github.com/skohub-io/skohub-vocabs/issues/109#issuecomment-749011998), but I guess why not 🙂

2021-01-15 08:49 UTC, acka47 commented
@dr0i, can you please deploy this on test?

2021-01-15 08:54 UTC, dr0i commented
Branch has conflicts, please resolve them first.

2021-01-15 08:58 UTC, acka47 commented
Ah, @sroertgen already said that he could resolve them. Assigning him.

2021-01-15 09:05 UTC, merged

2021-01-15 09:31 UTC, sroertgen commented
I'm sorry I accidentally merged into `master` directly.

2021-01-18 10:29 UTC, acka47 commented
@dr0i, can you please deploy `master` on test?

2021-01-18 10:39 UTC, dr0i commented
Deployed at test.

2021-01-18 12:27 UTC, acka47 commented
> Deployed at test.

Are you sure? I published https://github.com/acka47/hcrt/blob/master/hcrt.ttl to test and it has matching relations as wll as `related` in there but I can not see them in https://test.skohub.io/acka47/hcrt/heads/master/w3id.org/kim/hcrt/scheme.de.html – neither in the HTML nor in the JSON...

2021-01-18 14:35 UTC, dr0i commented
Yes , with 5ce5f05 as the HEAD:

> commit 5ce5f05d9d37020c0a9836dae55c5bd741325abc (HEAD -> master, origin/relatedMatch, origin/master, origin/HEAD)

Just redeployed it, without your desired outcome. The  `scripts/start.sh` is used, maybe there is a flaw in it?
I also did now `rm -rf .cache` as suggested in the README before running the start script, but this changes nothing.
And: is this working at production or is only test affected?

2021-01-19 09:31 UTC, acka47 commented
Now it looks good, see https://test.skohub.io/acka47/hcrt/heads/master/w3id.org/kim/hcrt/text.de.html. Will start my review then.

2021-01-19 10:47 UTC, dr0i commented
@acka47 just to deconfuse me , you wrote:

>  as related in there but I can not see them in https://test.skohub.io/acka47/hcrt/heads/master/w3id.org/kim/hcrt/scheme.de.html 

and I still cannot see these `related`. What do I miss?

2021-01-19 10:55 UTC, acka47 commented
> and I still cannot see these `related`. What do I miss? 

It's there now, see https://test.skohub.io/acka47/hcrt/heads/master/w3id.org/kim/hcrt/text.de.html

2021-01-19 11:20 UTC, dr0i commented
I see it's in `text.de.html` but is is in `scheme.de.html` ?

2021-01-19 11:28 UTC, acka47 commented
> I see it's in `text.de.html` but is is in `scheme.de.html` ?

I was a bit unclear in https://github.com/skohub-io/skohub-vocabs/pull/117#issuecomment-762218843. i referred to the concept scheme (`scheme`) but the changes can only be seen for concepts in that scheme (e.g. `text`).

2021-01-19 12:03 UTC, literarymachine commented
The links are there, but they are broken. They should point to the current language, e.g. `slide.de.html`.

2021-01-19 12:17 UTC, sroertgen commented
ah yes, the changes from i18n are not reflected there. This should be easy to fix. I guess we proceed in `master`? I can prepare the fix.

2021-01-19 12:31 UTC, acka47 commented
> I guess we proceed in master? 

+1

2021-01-19 12:45 UTC, sroertgen commented
See: a92b32324f3415b0520382afb9c9824275648b75

2021-01-19 13:18 UTC, acka47 commented
@dr0i please redeploy on test.

2021-01-19 16:28 UTC, dr0i commented
Deployed (as always by just doing this: killing the process - and wait for monit to kick in to execute start script).

2021-01-20 08:29 UTC, acka47 commented
Everything's fine now, please deploy to production, @dr0i .

2021-01-21 07:37 UTC, dr0i commented
Deployed to production.